/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassDataForm.java
 *
 * Created on Oct 2, 2012, 7:32:08 PM
 */

package org.school.ui.student;

import java.util.Date;
import javax.swing.JOptionPane;
import org.school.domain.clazz;
import org.school.manager.classManager;
import org.school.util.DateUtil;

/**
 *
 * @author Rafiq
 */
public class ClassDataForm extends javax.swing.JFrame {

    /** Creates new form ClassDataForm */
    public ClassDataForm() {
        initComponents();
        setSize(500,400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClassNo = new javax.swing.JTextField();
        txtClassDate = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Class Data Form 2012");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 36, 230, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Class No :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Class Date :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(51, 160, 80, 30);
        getContentPane().add(txtClassNo);
        txtClassNo.setBounds(150, 120, 170, 30);
        getContentPane().add(txtClassDate);
        txtClassDate.setBounds(150, 162, 170, 30);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton);
        SaveButton.setBounds(50, 260, 90, 30);

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResetButton);
        ResetButton.setBounds(160, 260, 100, 30);

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(280, 260, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
     if(classCompleteForm() == false)
        {
            return;
        }
        String id = txtClassNo.getText();
        String date = txtClassDate.getText();
        Date dt = DateUtil.getDateFromString(date);
        clazz  sc = new clazz(id, dt);
       boolean isSave = classManager. isSaveStudentWithPrepared(sc);
        if(isSave)
        {
            System.out.println("Succssfully Save class Data");
            clear();
        }
    else{
       System.out.println("sorry");
    }
    }//GEN-LAST:event_SaveButtonActionPerformed
public  void clear(){
    txtClassNo.setText("");
    txtClassDate.setText("");

}
    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
       clear();
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

     private boolean classCompleteForm(){

     if(txtClassNo.getText() == null || txtClassNo.getText().trim().isEmpty())
        {
            txtClassNo.setText("");
            JOptionPane.showMessageDialog(null, "Please Enter Class No", "Alert", JOptionPane.ERROR_MESSAGE);
            return false;
        }
 if(txtClassDate.getText() == null || txtClassDate.getText().trim().isEmpty())
        {
            txtClassDate.setText("");
            JOptionPane.showMessageDialog(null, "Please Enter class date", "Alert", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    return true;

}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassDataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtClassDate;
    private javax.swing.JTextField txtClassNo;
    // End of variables declaration//GEN-END:variables

}
