

package org.school.ui.student;

import javax.swing.JOptionPane;
import org.school.domain.Student;
import org.school.manager.StudentManager;


public class StudentDataForm extends javax.swing.JFrame {

    /** Creates new form StudentDataForm */
    public StudentDataForm() {
        super("Student Data Form");

        initComponents();
        setSize(500,400);
        setLocation(100,100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtMobileNo = new javax.swing.JTextField();
        cmbDepartmentName = new javax.swing.JComboBox();
        SaveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18));
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Student Data Entry Form 2012");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 16, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setForeground(new java.awt.Color(204, 0, 153));
        jLabel2.setText("Student ID      :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Student Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Mobile No        :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Dept. Name    :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 210, 94, 30);
        getContentPane().add(txtID);
        txtID.setBounds(170, 80, 170, 30);
        getContentPane().add(txtName);
        txtName.setBounds(170, 120, 170, 30);
        getContentPane().add(txtMobileNo);
        txtMobileNo.setBounds(170, 160, 170, 30);

        cmbDepartmentName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ICT", "CSE", "TEXTILE", "BBA", "FTNS", "MATH", "BGE", " ", " " }));
        getContentPane().add(cmbDepartmentName);
        cmbDepartmentName.setBounds(170, 210, 170, 30);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton);
        SaveButton.setBounds(170, 290, 90, 30);

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(280, 290, 90, 30);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/school/ui/student/Back.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(30, 293, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
    if(stCompleteForm() == false)
        {
            return;
        }
    String id = txtID.getText();
    String name = txtName.getText();
    String mobileNo = txtMobileNo.getText();
    String deptName = cmbDepartmentName.getSelectedItem().toString();
    Student studentObj = new Student(id, name, mobileNo,deptName);
    boolean isSave = StudentManager.isSaveStudentWithPrepared(studentObj);
    if(isSave){
        System.out.println("successful save");
       clear();
    }else{
       System.out.println("sorry");
    }
    }//GEN-LAST:event_SaveButtonActionPerformed
 public  void clear(){
    txtID.setText("");
    txtName.setText("");
    txtMobileNo.setText("");
    }
   private boolean stCompleteForm(){
          if(txtID.getText() == null || txtID.getText().trim().isEmpty())
        {
            txtID.setText("");
            JOptionPane.showMessageDialog(null, "Please Enter Student ID", "Alert", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtName.getText() == null || txtName.getText().trim().isEmpty())
        {
            txtName.setText("");
            JOptionPane.showMessageDialog(null, "Please Enter Student Name", "Alert", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(txtMobileNo.getText() == null || txtMobileNo.getText().trim().isEmpty())
        {
            txtMobileNo.setText("");
            JOptionPane.showMessageDialog(null, "Please Enter Student Mobile No", "Alert", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
     
       dispose();
      
         
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       this.hide();
       new MainWindow().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox cmbDepartmentName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
