/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * serch.java
 *
 * Created on Apr 18, 2010, 4:49:47 AM
 */

/**
 *
 * @author motiur
 */
import java.awt.*;
 import java.awt.event.*;
 import java.applet.*;
 import java.lang.String;
 import javax.swing.*;
 import java.sql.*;
public class serch_3 extends javax.swing.JFrame {
ResultSet rs;
           Statement sta;
           public static String a,a1,p1,p,p2,p3,a2,p4,p5,p6,p7,p8,p9;
    /** Creates new form serch */
    public serch_3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID:");

        jLabel2.setText("ID:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("NAME:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 3, 48));
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("SEARCH EMERGENCY  ONE");

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 3, 18));
        jButton1.setForeground(new java.awt.Color(255, 102, 51));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 3, 18));
        jButton2.setForeground(new java.awt.Color(0, 204, 153));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton3.setForeground(new java.awt.Color(255, 102, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial Black", 3, 18));
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial Black", 3, 18));
        jButton5.setForeground(new java.awt.Color(153, 153, 0));
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("sex:");

        jButton6.setFont(new java.awt.Font("Arial Black", 3, 18));
        jButton6.setForeground(new java.awt.Color(102, 0, 51));
        jButton6.setText("BY NAME");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setText("ADDRESS:");

        jLabel8.setText("ADMITTION DATE");

        jLabel9.setText("DISTRICT:");

        jLabel12.setText("AGE:");

        jLabel13.setText("RELEASED STATUS:");

        jLabel15.setText("DUE AMOUNT:");

        jLabel14.setText("RELEASED DATE:");

        jLabel16.setText("CABIN NO:");

        jButton7.setFont(new java.awt.Font("Monotype Corsiva", 3, 18));
        jButton7.setForeground(new java.awt.Color(153, 51, 255));
        jButton7.setText("PAID THE DUE AMOUNT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Monotype Corsiva", 3, 24));
        jButton8.setForeground(new java.awt.Color(0, 0, 102));
        jButton8.setText("RELEASED");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 204, 255));
        jButton9.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 51));
        jButton9.setText("TRANSFER TO GENERAL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(846, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(jTextField9)
                    .addComponent(jTextField6)
                    .addComponent(jTextField8)
                    .addComponent(jTextField7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jTextField12))))
                .addGap(773, 773, 773))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(1153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
emergency i=new emergency();
this.hide();
i.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Jdbc j=new Jdbc();
      j.connection();
       p3="";
      String id=jTextField1.getText();
      if(p3.equals(id))
      {
      JOptionPane.showMessageDialog(null,"FIRST  SELECT  AN  ID  OF  A  PATIENT, THEN  SEARCH  .......  ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
          String search=("select * from emergency where id='"+id+"'");
	rs=j. find_statement(search);
   try{
    while(rs.next())
    {
  
  jTextField2.setText(rs.getString(1));
  jTextField3.setText(rs.getString(2));
     jTextField5.setText(rs.getString(4));
   jTextField7.setText(rs.getString(12));
   jTextField8.setText(rs.getString(8));
   jTextField6.setText(rs.getString(6));
jTextField9.setText(rs.getString(5));
 jTextField12.setText(rs.getString(14));
jTextField14.setText(rs.getString(13));
jTextField13.setText(rs.getString(15));
jTextField15.setText(rs.getString(11));
    }
    
   }catch(Exception e){}
      }
       p9=jTextField2.getText();
    if(p3.equals(p9))
    {
     JOptionPane.showMessageDialog(null,"THERE  IS  NO  PATIENT  IN  THIS  ID .......PLEASE  ENTER  THE  CORRECT  ID  THEN  SEARCH...THANKS    FOR  SEARCH....  ","BAD NEWS",JOptionPane.WARNING_MESSAGE);

    }

      //txtsearchname.setText(search);
       j.connectionclose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
        jTextField3 .setText("");
    jTextField2.setText("");
   jTextField5.setText("");
   
    jTextField7.setText("");
   jTextField8.setText("");
   jTextField6.setText("");
      jTextField9.setText("");
     
      jTextField12.setText("");
      jTextField14.setText("");
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      Jdbc j=new Jdbc();
      j.connection();
       p2="";
      String id=jTextField1.getText();
      if(p2.equals(id))
      {
      JOptionPane.showMessageDialog(null,"FIRST  SELECT  AN  ID  OF  A  PATIENT, THEN  UPDATE  .......  ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
    String search=("update emergency set name="+"'" + jTextField3.getText()+ "'where id='"+ jTextField1.getText() +"'"); // TODO add your handling code here:
         j.createTable(search);
   
      String up =(" update emergency set age ="+"'" + jTextField9.getText()+ "' where id='"+ jTextField1.getText() +"'");
  String sex =(" update emergency set sex ="+"'" + jTextField5.getText()+ "' where id='"+ jTextField1.getText() +"'");
  String dis =(" update emergency set district ="+"'" + jTextField8.getText()+ "' where id='"+ jTextField1.getText() +"'");
String addr=(" update emergency set address="+"'" + jTextField6.getText()+ "' where id='"+ jTextField1.getText() +"'");
String bed=(" update emergency set bed_no="+"'" + jTextField15.getText()+ "' where id='"+ jTextField1.getText() +"'");
j.createTable(sex);
      j.createTable(up);
        j.createTable(dis);
      j.createTable(addr);
     j.createTable(bed);
      JOptionPane.showMessageDialog(null,"  SUCCESSFULLY  UPDATED  .......  ","GOOD NEWS",JOptionPane.WARNING_MESSAGE);
      }
         j.connectionclose();
         
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 Jdbc j=new Jdbc();
        j.connection();
         p1="";
      String id=jTextField1.getText();
      if(p1.equals(id))
      {
      JOptionPane.showMessageDialog(null,"FIRST  SELECT  AN  ID  OF  A  PATIENT, THEN  DELETE  .......  ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
         String del=" delete from  emergency where id=' "+ jTextField1.getText() +" '";
          j.createTable(del);


         JOptionPane.showMessageDialog(null," Entry deleted ..... ");
             jTextField1.setText(" ");
           jTextField2.setText(" ");
          jTextField3.setText(" ");
        
          jTextField5.setText(" ");
           jTextField6.setText(" ");
          jTextField7.setText(" ");
         jTextField8.setText(" ");
          jTextField9.setText(" ");
         
         
      }
    ///  JOptionPane.showMessageDialog(textCon, sta, del, WIDTH);
       j.connectionclose();//  delete        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
name_2 n=new name_2();
this.hide();
n.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Jdbc j=new Jdbc();
      j.connection();
        String u="no";
    String pass="0";
  String a = new String(jTextField12.getText());
   String p=new String(jTextField14.getText());
    p4="";
      String id=jTextField1.getText();
      if(p4.equals(id))
      {
      JOptionPane.showMessageDialog(null,"FIRST  SELECT  AN  ID  OF  A  PATIENT, THEN  RELEASED .......  ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
   if(p.equals(pass))
   {
       if(u.equals(a))
   {
   r_date_1 fp=new r_date_1();
this.hide();
fp.show();}
    else
     JOptionPane.showMessageDialog(null," SORRY HE/SHE IS A RELEASED PATIENT.......");
    }

    else

    JOptionPane.showMessageDialog(null," SORRY YOU CAN NOT RELEASED,FIRST PAID THE DUE AMOUNT.......");
   }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Jdbc j=new Jdbc();
      j.connection();
        String u="111";
    String pass="0";
  String a = new String(jTextField1.getText());
   String p=new String(jTextField14.getText());
   if(p.equals(pass))
   {
   JOptionPane.showMessageDialog(null," THE PATIENT HAS NO DUE AMOUNT.......");

   }
   else
  {
     paid_1 fp=new paid_1();
this.hide();
fp.show();


  }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Jdbc j=new Jdbc();
      j.connection();
        String u="no";
    String pass="0";
  String a = new String(jTextField12.getText());
   String p=new String(jTextField14.getText());
    p4="";
      String id=jTextField1.getText();
      if(p4.equals(id))
      {
      JOptionPane.showMessageDialog(null,"FIRST  SELECT  AN  ID  OF  A  PATIENT, THEN  TRANSFER TO  EMERGENCY .......  ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
      }
      else
      {
     if(a.equals(u))
     {
         String addr=jTextField6.getText();
       String idd=jTextField2.getText();
        String pnm=jTextField3.getText();
     //String fnm=jTextField2.getText();
   // String vill=jTextField4.getText();
       String dist=jTextField8.getText();
       String sex=jTextField5.getText();
         String age=jTextField9.getText();
   String bed=jTextField15.getText();
 String admdate=jTextField7.getText();
   String due=jTextField14.getText();
   //Object cabin=jComboBox2.getSelectedItem();
    // Object reff=jComboBox1.getSelectedItem();

      // j.createTable("create table patient(id varchar(20),name varchar(20),fathers_name varchar(40),sex varchar(10),age varchar(10),address varchar(50),village varchar(50),district varchar(30),refference_by varchar(20),ward_no varchar(30),bed_no varchar(20),admition_date varchar(20),due_amount varchar(20),released_status varchar(30),released_date varchar(30),primary key (id))");
     // j.createTable("insert into patient values ('"+fnm+"','"+pnm+"','not entered','"+sex+"','"+age+"','"+addr+"','not entered','"+dist+"','RELATIVE','AC CABIN','"+bed+"','"+admdate+"','"+due+"','no','not released')");
  //j.createTable("insert into patient_1 values ('"+id+"','"+name+"','"+lme+"','"+fnm+"','"+sex+"','"+adr+"','"+vill+"','"+dept+"','"+admt+"','"+date+"','"+age+"','"+hous+"','"+dstr+"','"+mbl+"','"+adat+"','no','"+cabin+"','"+due+"','not released')");
   j.createTable("insert into patient_1 values ('"+idd+"','"+pnm+"','not entered','not entered','"+sex+"','"+addr+"','not entered','EMERGENCY','OWN','"+admdate+"','"+age+"','not entered','"+dist+"','not entered','CABIN','no','"+bed+"','"+due+"','not released')");
   String del=(" delete from emergency where id='"+ jTextField1.getText() +"'");
   j.createTable(del);
 JOptionPane.showMessageDialog(null," YOU  ARE  SUCCESSFULLY  TRASNFERED  TO  THE  GENERAL  DEPARTMENT...... ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
  jTextField1.setText("");
        jTextField3 .setText("");
    jTextField2.setText("");
   jTextField5.setText("");
   //jTextField4.setText("");
    jTextField7.setText("");
   jTextField8.setText("");
   jTextField6.setText("");
      jTextField9.setText("");
      //jTextField10.setText("");
      //jTextField11.setText("");
      jTextField12.setText("");
      jTextField14.setText("");
       jTextField13.setText("");
      jTextField15.setText("");
      }
     else
     {


      JOptionPane.showMessageDialog(null," HE / SHE  IS  A  RELEASED  PATIENT  ...... ","BAD NEWS",JOptionPane.WARNING_MESSAGE);
     }}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
       
   
   
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
